### ISSUE TITLE
(Bug) including coveralls brokes CI

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#609]
Relates to https://github.com/poanetwork/token-wizard/pull/599
![screen shot 2018-02-20 at 13 32 11](https://user-images.githubusercontent.com/4341812/36419298-8b693340-1642-11e8-8c2b-ac2d6e82a660.png)

 ```
FAIL  src/stores/GasPriceStore.spec.js
  ● Test suite failed to run
    TypeError: _GasPriceStore2.default is not a constructor
      
      at Object.<anonymous> (src/stores/index.js:38:72)
      at Object.<anonymous> (src/utils/utils.js:315:153)
      at Object.<anonymous> (src/stores/GasPriceStore.js:3:40)
      at Object.<anonymous> (src/stores/GasPriceStore.spec.js:5:48)
          at <anonymous>
```

**Comment by fvictorio** [comment]
Oh, that's strange. I'll look into it ASAP.
