### ISSUE TITLE
I have a problem - errors reported cant get past stage 4

### ISSUE THREAD

**Issue by SoccerCoins** [poanetwork/token-wizard#882]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

from wallet: 0xBDA528b552fd028bbac396E9649894C91d3eFE64

### If you were able to create it, what is the URL of your crowdsale?

at stage 4 when i get error message saying transaction not valid

### Do you have screenshots showing the problem?

[wizard.poa.network-1526403805944.log](https://github.com/poanetwork/token-wizard/files/2005952/wizard.poa.network-1526403805944.log)

### Do you see errors in the dev console? If yes, please include a screenshot

Array(2)0: 401: Error: Returned error: Error: gas required exceeds allowance or always failing transaction
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237
    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046
    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237
    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046
    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237
    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046
    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)
    at Object.ErrorResponse (https://wizard.poa.network/static/js/main.214d01fe.js:1:1688223)
    at https://wizard.poa.network/static/js/main.214d01fe.js:1:1806373
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:87254
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:6790
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25021)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:6790
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9896)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9818)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:86619
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:88203
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:19233
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9910)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9934
    at ze (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:19303)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10023)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:88169)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:87736
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:24965)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25043)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620
From previous event:
    at i.p [as _captureStackTrace] (https://wizard.poa.network/static/js/main.214d01fe.js:1:1719780)
    at i._then (https://wizard.poa.network/static/js/main.214d01fe.js:1:1749130)
    at i.then (https://wizard.poa.network/static/js/main.214d01fe.js:1:1747498)
    at https://wizard.poa.network/static/js/main.214d01fe.js:1:942865
    at https://wizard.poa.network/static/js/main.214d01fe.js:1:1011605message: "Returned error: Error: gas required exceeds allowance or always failing transaction↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237↵    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)↵    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)↵    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046↵    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)"stack: "Error: Returned error: Error: gas required exceeds allowance or always failing transaction↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237↵    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)↵    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)↵    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046↵    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1391377↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927906↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364324)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349237↵    at Ht (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:358606)↵    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349326)↵    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928821)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928388↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928354↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364268)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:364346)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928727↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349733↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:346093↵    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349199)↵    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349121)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:348923↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:349713↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:928609↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:927046↵    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1066207)↵    at Object.ErrorResponse (https://wizard.poa.network/static/js/main.214d01fe.js:1:1688223)↵    at https://wizard.poa.network/static/js/main.214d01fe.js:1:1806373↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:87254↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:6790↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25021)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:6790↵    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9896)↵    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9818)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:86619↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:88203↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:19233↵    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9910)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9934↵    at ze (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:19303)↵    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10023)↵    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:88169)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:87736↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:24965)↵    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25043)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9620↵From previous event:↵    at i.p [as _captureStackTrace] (https://wizard.poa.network/static/js/main.214d01fe.js:1:1719780)↵    at i._then (https://wizard.poa.network/static/js/main.214d01fe.js:1:1749130)↵    at i.then (https://wizard.poa.network/static/js/main.214d01fe.js:1:1747498)↵    at https://wizard.poa.network/static/js/main.214d01fe.js:1:942865↵    at https://wizard.poa.network/static/js/main.214d01fe.js:1:1011605"__stackCleaned__: true__proto__: Objectlength: 2__proto__: Array(0)concat: ƒ concat()arguments: (...)caller: (...)length: 1name: "concat"__proto__: ƒ ()[[Scopes]]: Scopes[0]constructor: ƒ Array()arguments: (...)caller: (...)from: ƒ from()isArray: ƒ isArray()length: 1name: "Array"of: ƒ of()prototype: [constructor: ƒ, concat: ƒ, find: ƒ, findIndex: ƒ, pop: ƒ, …]Symbol(Symbol.species): (...)get Symbol(Symbol.species): ƒ [Symbol.species]()__proto__: ƒ ()[[Scopes]]: Scopes[0]copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flatMap: ƒ (t)flatten: ƒ ()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object
handleError @ index.js:128

*Your answer*

---

**Comment by vbaranov** [comment]
@SoccerCoins which transaction did cause the issue? Do you have a screenshot of step 4 page? Could you describe steps before this error? Which gas price did you use for transaction?

**Comment by SoccerCoins** [comment]
![error screenshot](https://user-images.githubusercontent.com/37705089/40075490-50a501ca-5874-11e8-81db-80ece6f1dbc0.png)
after the earlier hiccup I used 12 gwei and the default gas throughout got the success screen at the end of stage 3 and moved on and then it showed this error

**Comment by SoccerCoins** [comment]
helllloooo? insta reply to new threads then nothing...?

**Comment by vbaranov** [comment]
It is closed because no any comments. Describe what happens after these steps:
>Steps to get summary files: refresh the step 4 screen, reject transaction in MetaMask, click "Skip transaction" button, Download files and go to your crowdsale page.

**Comment by SoccerCoins** [comment]
I think I should start again as due to the delays in deploy because of the gwei error the first tier has closed and it is a mess of a deploy

Would you be willing to refund any of the costs?

**Comment by vbaranov** [comment]
There are no errors in gwei. Gas price was calculated for the Safe and Cheap option as default. If you wanted to create crowdsale faster you need to choose higher a gas price in step 3 of Wizard. We are not responsible for a long transactions mining in Mainnet. Your crowdsale is alive. I gave you the links. There is no way to refund in this case.

**Comment by SoccerCoins** [comment]
ok thanks - as i said was form my errors before this fault I cant get past lets call it closed thanks, I will deploy a new one
