### ISSUE TITLE
Transaction error from Metamask

### ISSUE THREAD

**Issue by jun-henin** [poanetwork/token-wizard#940]
### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten network

### Do you have screenshots showing the problem?

Transaction error from Metamask during deployment

### Do you see errors in the dev console? If yes, please include a screenshot
![image](https://user-images.githubusercontent.com/18493363/40981020-e4d806b6-6914-11e8-8277-60db7ed75ce9.png)

blockchainHelpers.js:166 Error: Returned error: Error: Error: [ethjs-rpc] rpc error with payload {"id":4912676518033,"jsonrpc":"2.0","params":["0xf8892385021e66fb0083023a6b94897e4770c5cca3665e01385b77b258f24b0c80c580a419b667da000000000000000000000000b0eddd7357340a728137d41249267ffa1e86699d2aa0860bcb29f12ca647389578fa319e217413820ade334541216091db9146255baca0590e86d2a8cc5b4b395ee2e04d6b8d7a02248ba37d762582c8ed87d2f651b0d6"],"method":"eth_sendRawTransaction"} Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1328845700000000 and got: 0.
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:38080)
    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:583428)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:584992
    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:585062)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89967)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89569)
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:41649)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as throw] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390977
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:38080)
    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:583428)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:584992
    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:585062)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89967)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89569)
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:41649)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as throw] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390977
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:38080)
    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:583428)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:584992
    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:585062)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89967)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:89569)
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:41649)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087652)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087440)
    at Generator.e.(anonymous function) [as throw] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:1087831)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390856)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1:390977
    at Object.ErrorResponse (https://wizard.oracles.org/static/js/main.0c733666.js:1:1701489)
    at https://wizard.oracles.org/static/js/main.0c733666.js:1:1819639
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:87210
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:6746
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:24977)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9576
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:6746
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9852)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9774)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9576
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:86575
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:88159
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:19189
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9866)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9890
    at ze (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:19259)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9979)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:88125)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:87692
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:24921)
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:24999)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1:9576
From previous event:
    at i.p [as _captureStackTrace] (https://wizard.oracles.org/static/js/main.0c733666.js:1:1733046)
    at i._then (https://wizard.oracles.org/static/js/main.0c733666.js:1:1762396)
    at i.then (https://wizard.oracles.org/static/js/main.0c733666.js:1:1760764)
    at https://wizard.oracles.org/static/js/main.0c733666.js:1:951123
    at https://wizard.oracles.org/static/js/main.0c733666.js:1:1024872
(anonymous) @ blockchainHelpers.js:166
i.emit @ index.js:89
(anonymous) @ index.js:83
setTimeout (async)
u @ index.js:82
o @ index.js:472
(anonymous) @ index.js:137
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
o @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
u @ inpage.js:1
s @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
ze @ inpage.js:1
(anonymous) @ inpage.js:1
value @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
o @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
o @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
u @ inpage.js:1
s @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
setTimeout (async)
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
g.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
a.emit @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
v.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
g.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
a.emit @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
v.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
c._write @ contentscript.js:1
L @ contentscript.js:1
(anonymous) @ contentscript.js:1
n.write @ contentscript.js:1
I @ contentscript.js:1
(anonymous) @ contentscript.js:1
m.emit @ contentscript.js:1
V @ contentscript.js:1
a @ contentscript.js:1
o.push @ contentscript.js:1
c._onMessage @ contentscript.js:1
EventImpl.dispatchToListener @ VM63 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM69 extensions::utils:138
EventImpl.dispatch_ @ VM63 extensions::event_bindings:387
EventImpl.dispatch @ VM63 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM69 extensions::utils:138
dispatchOnMessage @ VM83 extensions::messaging:392
index.js:128 (2) [25, Error: Returned error: Error: Error: [ethjs-rpc] rpc error with payload {"id":4912676518033,"jsonrpc…]
handleError @ index.js:128
Promise.catch (async)
resumeContractDeployment @ index.js:110
(anonymous) @ index.js:143
Promise.then (async)
skipTransaction @ index.js:136
r @ ReactErrorUtils.js:24
a @ EventPluginUtils.js:83
s @ EventPluginUtils.js:106
d @ EventPluginHub.js:41
m @ EventPluginHub.js:52
r @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:252
r @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
o @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
o @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145

**Comment by vbaranov** [comment]
@jun-henin 
what version of Metamask do you use?
what account address is unlocked in Metamask?

**Comment by vbaranov** [comment]
@jun-henin 
the issue is with Ropsten itself. There is announcement in https://ropsten.etherscan.io/:
>Announcement: We are experiencing synching issues on ropsten, indexing has temporarily been paused
